####
POST  http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "john",
    "email": "john@gmail.com",
    "password": "123456"
}

###
POST  http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "username": "raj",
    "password": "12345"
}

###
GET  http://localhost:8800/api/test/should-be-logged-in

###
GET  http://localhost:8800/api/user/665f553227c7dfa2d14da4db

###
PUT http://localhost:8800/api/user/665f553227c7dfa2d14da4db
Content-Type: application/json

{
    "username":"raj_2"
}

###
GET http://localhost:8800/api/posts