####
POST  http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "john",
    "email": "john@gmail.com",
    "password": "123456"
}

###
POST  http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "username": "john",
    "password": "123456"
}

###
GET  http://localhost:8800/api/test/should-be-logged-in

###
GET  http://localhost:8800/api/user/665f4ae3f591ee6f3765417a

###
PUT http://localhost:8800/api/user/665f4ae3f591ee6f3765417a
Content-Type: application/json

{
    "username":"rahul_1"
}